In [1]:
from src.trainer import s2sTrainer
from src.data import DeEndataset
from torch.utils.data import DataLoader
import torch
import sys
from src.seq2seq import Encoder, Decoder, seq2seq

train_data_paths = [
        "/home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.de",
        "/home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.en"
    ]

TrainDataset = DeEndataset(train_data_paths)

encoder_config = {
    "emb_dim" : 1000,
    "hid_dim" : 1000,
    "lstm_layers" : 4,
    "num_embeddings" : len(TrainDataset.src_vocab),
    "pad_idx" : TrainDataset.src_vocab.pad_idx
}

decoder_config = {
    "emb_dim" : 1000,
    "hid_dim" : 1000,
    "lstm_layers" : 4,
    "num_embeddings" : len(TrainDataset.dst_vocab),
    "pad_idx" : TrainDataset.dst_vocab.pad_idx,
    "output_dim" : len(TrainDataset.dst_vocab)
}

encoder = Encoder(**encoder_config)
decoder = Decoder(**decoder_config)
seq2seq = seq2seq(encoder, decoder)
TrainDataset.src_vocab.build_index_dict()
TrainDataset.dst_vocab.build_index_dict()

In [2]:
Trainloader = DataLoader(TrainDataset, batch_size = 10, collate_fn=TrainDataset.collate_fn)

In [3]:
for tl in Trainloader:
    break

In [26]:
tl[1]

tensor([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 4, 15, 21, 21,  4, 21, 21, 21, 21, 70],
        [ 5, 16, 25, 31, 16, 31, 31, 55, 63, 71],
        [ 6, 17, 26, 17,  9, 17, 34, 26, 64, 36],
        [ 7, 18, 27, 21, 40, 45, 52, 56, 21, 72],
        [ 8, 19, 28, 32, 41, 46, 40, 36, 65, 17],
        [ 9,  9, 21, 33, 42, 21, 21, 57, 66, 41],
        [10, 20, 29, 34, 43, 47, 53, 58, 34, 73],
        [11, 21, 30, 35, 44, 48, 54, 48, 67, 74],
        [12, 22, 14, 36, 14, 41,  3, 59, 68, 41],
        [13, 23,  3, 21,  3, 49,  0, 60, 21, 75],
        [14, 24,  0, 37,  0, 31,  0, 61, 69, 14],
        [ 3, 14,  0, 38,  0, 50,  0, 41, 14,  3],
        [ 0,  3,  0, 21,  0, 51,  0, 62,  3,  0],
        [ 0,  0,  0, 39,  0, 33,  0, 14,  0,  0],
        [ 0,  0,  0, 14,  0, 14,  0,  3,  0,  0],
        [ 0,  0,  0,  3,  0,  3,  0,  0,  0,  0]])

In [23]:
a, (b,c) = seq2seq.encoder.lstm(seq2seq.encoder.emb(tl[0][0]))

In [28]:
seq2seq.decoder.lstm(seq2seq.decoder.emb(tl[1]), (b,c))

(tensor([[[-1.8653e-03, -4.2058e-03, -2.5996e-03,  ..., -1.2797e-02,
           -4.5491e-03,  5.0520e-03],
          [-3.9029e-03, -3.5952e-03, -5.5277e-03,  ..., -9.6980e-03,
           -4.4721e-03,  8.3763e-03],
          [-5.4942e-03, -5.6568e-03, -3.7973e-03,  ..., -1.2518e-02,
           -4.3796e-03,  4.1578e-03],
          ...,
          [-1.3721e-03, -4.9914e-03, -2.5080e-04,  ..., -1.2988e-02,
           -4.6839e-03,  5.9958e-03],
          [-5.2516e-03, -6.1249e-03, -4.6869e-03,  ..., -1.1568e-02,
           -3.6474e-03,  5.5232e-03],
          [-3.7354e-03, -6.7820e-03, -1.8859e-03,  ..., -1.4510e-02,
           -4.2517e-03,  5.3503e-03]],
 
         [[-1.9114e-03, -7.3917e-04, -7.0411e-03,  ..., -1.5726e-02,
           -8.6957e-03,  4.3373e-03],
          [-3.0824e-03, -8.6521e-04, -8.3094e-03,  ..., -1.4446e-02,
           -8.2494e-03,  6.8452e-03],
          [-3.3405e-03, -1.9820e-03, -5.8452e-03,  ..., -1.6559e-02,
           -9.1148e-03,  4.0979e-03],
          ...,
    

In [12]:
a, b = seq2seq.encoder(tl[0][0])

In [18]:
tl[0][0].T.size()

torch.Size([10, 18])

In [13]:
a.size()

torch.Size([4, 18, 1000])

In [17]:
seq2seq(tl[0][0].T, tl[1])

tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[-0.0070, -0.0298,  0.0007,  ...,  0.0212, -0.0067, -0.0144],
         [-0.0059, -0.0310,  0.0026,  ...,  0.0214, -0.0056, -0.0143],
         [-0.0067, -0.0310,  0.0013,  ...,  0.0212, -0.0069, -0.0141],
         ...,
         [-0.0067, -0.0293,  0.0005,  ...,  0.0222, -0.0073, -0.0146],
         [-0.0066, -0.0307,  0.0019,  ...,  0.0215, -0.0053, -0.0147],
         [-0.0063, -0.0301,  0.0010,  ...,  0.0217, -0.0060, -0.0145]],

        [[-0.0094, -0.0341,  0.0023,  ...,  0.0187, -0.0036, -0.0127],
         [-0.0091, -0.0348,  0.0031,  ...,  0

In [6]:
from torch.nn.utils.rnn import pack_padded_sequence
pack_padded_sequence(tl[0][0],tl[0][1])

RuntimeError: `lengths` array must be sorted in decreasing order when `enforce_sorted` is True. You can pass `enforce_sorted=False` to pack_padded_sequence and/or pack_sequence to sidestep this requirement if you do not need ONNX exportability.

In [4]:
print(tl)

((tensor([[ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [21,  3,  0,  0,  0,  0,  0,  0,  0,  0],
        [29, 21,  3,  0,  0,  0,  0,  0,  0,  0],
        [11, 29, 21,  3,  0,  0,  0,  0,  0,  0],
        [46, 11, 60,  4,  3,  0,  0,  0,  0,  0],
        [47, 30, 24,  5, 48,  0,  0,  0,  0,  0],
        [48, 31, 61,  6, 69,  3,  3,  0,  0,  0],
        [49, 32, 18,  7, 18, 21,  4,  3,  0,  0],
        [50, 33, 62,  8, 35, 23,  7, 75,  3,  3],
        [51, 34, 63,  9, 70, 24, 40, 76, 17, 21],
        [12, 35, 51, 10, 71, 25, 41, 77,  7, 29],
        [52, 36, 64, 11, 72, 11, 42, 11, 18, 55],
        [29, 37, 65, 12, 59, 21, 37, 12, 19, 56],
        [53, 38, 66, 13, 30, 26, 43, 78, 20, 57],
        [32, 21, 67, 14, 73, 27, 44, 34, 21, 58],
        [54, 39, 68, 15, 74, 28, 45, 79, 22, 59],
        [16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2]]), tensor([18, 17, 16, 15, 14, 12, 12, 11, 10, 10])), tensor([[ 0,  0,  0,  3,  0,  3,  0,  0,  0, 

In [22]:
print(tl)

((tensor([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [16, 16, 16, 16, 16, 16, 16, 16, 16, 16],
        [54, 39, 68, 15, 74, 28, 45, 79, 22, 59],
        [32, 21, 67, 14, 73, 27, 44, 34, 21, 58],
        [53, 38, 66, 13, 30, 26, 43, 78, 20, 57],
        [29, 37, 65, 12, 59, 21, 37, 12, 19, 56],
        [52, 36, 64, 11, 72, 11, 42, 11, 18, 55],
        [12, 35, 51, 10, 71, 25, 41, 77,  7, 29],
        [51, 34, 63,  9, 70, 24, 40, 76, 17, 21],
        [50, 33, 62,  8, 35, 23,  7, 75,  3,  3],
        [49, 32, 18,  7, 18, 21,  4,  3,  0,  0],
        [48, 31, 61,  6, 69,  3,  3,  0,  0,  0],
        [47, 30, 24,  5, 48,  0,  0,  0,  0,  0],
        [46, 11, 60,  4,  3,  0,  0,  0,  0,  0],
        [11, 29, 21,  3,  0,  0,  0,  0,  0,  0],
        [29, 21,  3,  0,  0,  0,  0,  0,  0,  0],
        [21,  3,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 3,  0,  0,  0,  0,  0,  0,  0,  0,  0]]), tensor([18, 17, 16, 15, 14, 12, 12, 11, 10, 10])), tensor([[ 2,  2,  2,  2,  2,  2,  2,  2,  2, 

In [24]:
enc_hidden, enc_cell = seq2seq.encoder(tl[0][0], tl[0][1])

In [27]:
output = seq2seq(tl[0][0], tl[0][1], tl[1])

In [41]:
output.view(-1, 9795).size()

torch.Size([170, 9795])

In [42]:
tl[1].reshape(-1)

tensor([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  4, 15, 21, 21,  4, 21, 21, 21,
        21, 70,  5, 16, 25, 31, 16, 31, 31, 55, 63, 71,  6, 17, 26, 17,  9, 17,
        34, 26, 64, 36,  7, 18, 27, 21, 40, 45, 52, 56, 21, 72,  8, 19, 28, 32,
        41, 46, 40, 36, 65, 17,  9,  9, 21, 33, 42, 21, 21, 57, 66, 41, 10, 20,
        29, 34, 43, 47, 53, 58, 34, 73, 11, 21, 30, 35, 44, 48, 54, 48, 67, 74,
        12, 22, 14, 36, 14, 41,  3, 59, 68, 41, 13, 23,  3, 21,  3, 49,  0, 60,
        21, 75, 14, 24,  0, 37,  0, 31,  0, 61, 69, 14,  3, 14,  0, 38,  0, 50,
         0, 41, 14,  3,  0,  3,  0, 21,  0, 51,  0, 62,  3,  0,  0,  0,  0, 39,
         0, 33,  0, 14,  0,  0,  0,  0,  0, 14,  0, 14,  0,  3,  0,  0,  0,  0,
         0,  3,  0,  3,  0,  0,  0,  0])

In [35]:
output.size()

torch.Size([17, 10, 9795])

In [37]:
loss_fn = torch.nn.CrossEntropyLoss(ignore_index = 0)

In [61]:
output.view(-1, 9795)[10]

tensor([2.0325e-01, 9.0797e-02, 7.4605e-02,  ..., 6.0461e-05, 8.0720e-02,
        6.6195e-02], grad_fn=<SelectBackward>)

In [50]:
output.view(-1, 9795)[20]

tensor([ 0.1088,  0.0678,  0.0490,  ...,  0.0028,  0.0644, -0.0093],
       grad_fn=<SelectBackward>)

In [43]:
loss_fn(output.view(-1, 9795), tl[1].reshape(-1))

tensor(9.2013, grad_fn=<NllLossBackward>)

In [12]:
src = "Zwei junge weiße Männer sind im Freien in der Nähe vieler Büsche."
test_sample = torch.Tensor([TrainDataset.src_vocab.stoi(src.lower(), option="seq2seq", reverse=True)]).long().view(-1,1)

In [ ]:
seq2seq.encoder

In [80]:
!head -2 /home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.de /home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.en

==> /home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.de <==
Zwei junge weiße Männer sind im Freien in der Nähe vieler Büsche.
Mehrere Männer mit Schutzhelmen bedienen ein Antriebsradsystem.

==> /home/jack/torchstudy/2week/1_refcode/.data/multi30k/train.en <==
Two young, White males are outside near many bushes.
Several men in hard hats are operating a giant pulley system.


In [91]:
src = "Mehrere Männer mit Schutzhelmen bedienen ein Antriebsradsystem."
test_sample = torch.Tensor([TrainDataset.src_vocab.stoi(src.lower(), option="seq2seq", reverse=True)]).long().view(-1,1)

In [92]:
for i in test_sample:
    print(TrainDataset.src_vocab.index_dict[int(i[0])])

<SOS>
.
antriebsradsystem
ein
bedienen
schutzhelmen
mit
männer
mehrere
<EOS>


In [94]:
seq2seq.load_state_dict(torch.load("./seq2seq-model.pt"))
outs, probs = [], []
break_point = 20
trial = 1
now_token = torch.Tensor([2]).to(torch.int64)
with torch.no_grad():
    emb = seq2seq.encoder.emb(test_sample)
    out, (hidden, cell) = seq2seq.encoder.lstm(emb) 
    while True:
        output, hidden, cell = seq2seq.decoder(now_token, hidden, cell)
        next_index = int(output.argmax())
        if next_index == 3:
            break

        outs.append(next_index)
        now_token = torch.Tensor([next_index]).long()
#         probs.append(float(torch.nn.Softmax(dim=2)(output).max()))

        trial += 1
        if trial == break_point:
            break

In [95]:
" ".join([TrainDataset.dst_vocab.index_dict[index] for index in outs if TrainDataset.dst_vocab.index_dict[index] != "<PAD>"])

'a man in a blue shirt is standing in front of a building .'

In [6]:
now_token = torch.Tensor([[next_index]]).to(torch.int64)
output, hidden, cell = seq2seq.decoder(now_token, hid, cell)
next_index = int(output.argmax())

In [7]:
next_index

4576

In [4]:
pred, pred_probs = seq2seq.predict(test_sample)

In [ ]:
pred

In [57]:
output, hidden, cell = seq2seq.decoder(now_token, hidden, cell)

In [59]:
cell.size()

torch.Size([4, 1, 1000])

In [56]:
src = "Jungen tanzen mitten in der Nacht auf Pfosten."
test_sample = torch.Tensor([[TrainDataset.src_vocab.stoi(src.lower(), option="seq2seq", reverse=True)]]).long()

seq2seq.load_state_dict(torch.load("./seq2seq-model.pt"))

test_sample = torch.reshape(test_sample, (-1,1))
pred, pred_probs = seq2seq.predict(test_sample)

# print(pred)
# print(TrainDataset.dst_vocab.itos(pred))



RuntimeError: Expected hidden[0] size (4, 1, 1000), got [4, 11, 1000]

In [33]:
hidden, cell = seq2seq.encoder.predict(test_sample)

In [35]:
hidden.size()

torch.Size([4, 1, 1000])

In [36]:
cell.size()

torch.Size([4, 1, 1000])

In [47]:
now_token_emb.size()

torch.Size([1, 1, 1000])

In [54]:
now_token = torch.Tensor([[4758]]).to(torch.int64)
now_token_emb = seq2seq.decoder.emb(now_token)
output, (hidden, cell) = seq2seq.decoder.lstm(now_token_emb, (hidden, cell))
output = seq2seq.decoder.fc_out(output)
int(output.argmax())
# next_index = int(output.argmax())
# if next_index == eos_idx:
#     break

# outs.append(next_index)
# now_token = torch.Tensor([next_index]).to(torch.int64)
# probs.append(float(torch.nn.Softmax(dim=2)(output).max()))


4758

In [ ]:
seq2seq.predict()

In [49]:
output.size()

torch.Size([1, 1, 1000])

In [27]:
output

tensor([[[ -9.2795,  -8.9954,  -7.7406,  ..., -10.4585,  -8.8203,  -5.4389]]],
       grad_fn=<AddBackward0>)

In [20]:

    def predict(self, inputs, input_len, sos_token=2, eos_idx=3):
        hidden, cell = self.encoder(inputs, torch.tensor([input_len]).long())

        outs = []
        probs = []

        now_token = torch.Tensor([sos_token]).to(torch.int64)
        trial = 0
        break_point = 100
        with torch.no_grad():
            while True:
                output, hidden, cell = self.decoder(now_token, hidden, cell)
                next_index = int(output.argmax())
                if next_index == eos_idx:
                    break

                outs.append(next_index)
                now_token = torch.Tensor([next_index]).to(torch.int64)
                probs.append(float(torch.nn.Softmax(dim=2)(output).max()))

                trial += 1
                if trial == break_point:
                    break
        return outs, probs

SyntaxError: unexpected EOF while parsing (<ipython-input-20-320ba166d17a>, line 1)

In [22]:
indices = list(test_sample.numpy().flatten())
[TrainDataset.src_vocab.index_dict[index] for index in indices if TrainDataset.src_vocab.index_dict[index] != "<PAD>"]

['<SOS>',
 '.',
 'pfosten',
 'auf',
 'nacht',
 'der',
 'in',
 'mitten',
 'tanzen',
 'jungen',
 '<EOS>']

In [26]:
[TrainDataset.dst_vocab.index_dict[index] for index in outs if TrainDataset.dst_vocab.index_dict[index] != "<PAD>"]

['workers',
 'members',
 'i',
 'to',
 'to',
 '"',
 '"',
 '"',
 '"',
 '"',
 '"',
 '"',
 '"',
 '"',
 '"',
 '.',
 '.',
 '.',
 '.']

In [27]:
pred

[21, 31, 17, 21, 90, 33, 34, 35, 17, 111, 74, 21, 65, 489, 14]

In [ ]:
def itos(self, indices):
    if type(indices) == int:
        return " ".join([self.index_dict[index] for index in indices if self.index_dict[index] != "<PAD>"])
    elif type(indices[0]) == list:
        return [self.itos(i) for i in indices]